name: Publish

on:
  push:
    branches:
      - master

# https://docs.npmjs.com/trusted-publishers#github-actions-configuration
permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: wyvox/action-setup-pnpm@v3
        with: { node-version: 24 }

      - name: upgrade npm
        run: npm install -g npm@latest

      - name: start qbittorrent
        # creates a default config with password adminadmin
        run: |
          mkdir -p ~/.config/qBittorrent/
          cat > ~/.config/qBittorrent/qBittorrent.conf << 'EOF'
          [BitTorrent]
          Session\QueueingSystemEnabled=false
          [Meta]
          MigrationVersion=6
          [Preferences]
          WebUI\Password_PBKDF2="@ByteArray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWVT9wVvdDtHAjU9b3b7uB8NR1Gur2hmQCvCDpm39Q+PsJRJPaCU51dEiz+dTzh8qbPsL8WkFljQYFQ==)"
          EOF
          sudo add-apt-repository ppa:qbittorrent-team/qbittorrent-stable
          sudo apt update
          sudo apt install qbittorrent-nox
          qbittorrent-nox -d
          sudo mkdir /downloads
          mkdir ~/downloads

      - name: lint
        run: pnpm run lint

      - name: build
        run: pnpm run build

      - name: test
        run: pnpm run test:ci

      - name: release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

