name: Publish

on:
  push:
    branches:
      - master

# https://docs.npmjs.com/trusted-publishers#github-actions-configuration
permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: wyvox/action-setup-pnpm@v3
        with: { node-version: 24 }

      - name: upgrade npm
        run: npm install -g npm@latest

      - name: release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
